#!/bin/bash
# nerve-up.sh — start the nerve CLI server on-demand (port 20128)
#
# Uses the launchd plist generated by install-nerve-server.sh.
# The plist is kept with a .disabled suffix so launchd doesn't auto-start
# it at login — nerve-up symlinks it to the active name and bootstraps it.
#
# Usage: nerve-up

set -euo pipefail

PLIST="$HOME/Library/LaunchAgents/com.vikas.nerve.plist.disabled"
ACTIVE="$HOME/Library/LaunchAgents/com.vikas.nerve.plist"

if launchctl print gui/$(id -u)/com.vikas.nerve 2>/dev/null | grep -q "state = running"; then
  echo "nerve is already running"
  exit 0
fi

if [ ! -f "$PLIST" ]; then
  echo "nerve plist not found at $PLIST"
  echo "Run scripts/ops/install-nerve-server.sh first."
  exit 1
fi

ln -sf "$PLIST" "$ACTIVE"
launchctl bootstrap gui/$(id -u) "$ACTIVE" 2>/dev/null
echo "Starting nerve on port 20128..."

for i in $(seq 1 30); do
  if curl -s http://localhost:20128/api/health >/dev/null 2>&1; then
    echo "nerve is ready (took ${i}s)"
    exit 0
  fi
  sleep 1
done
echo "nerve didn't become ready in 30s"
exit 1
